"""phase 0b initial schema

Revision ID: 7f491f98f46e
Revises:
Create Date: 2026-07-28 21:15:14.660548
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "7f491f98f46e"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "api_raw_responses",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("provider", sa.String(length=64), nullable=False),
        sa.Column("function_name", sa.String(length=160), nullable=False),
        sa.Column("endpoint", sa.String(length=600), nullable=True),
        sa.Column("request_params_hash", sa.String(length=64), nullable=False),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("as_of_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("http_status", sa.Integer(), nullable=True),
        sa.Column("response_body", sa.Text(), nullable=True),
        sa.Column("response_hash", sa.String(length=64), nullable=True),
        sa.Column("normalized_success", sa.Boolean(), nullable=True),
        sa.Column("data_state", sa.String(length=32), nullable=False),
        sa.Column("error_code", sa.String(length=120), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "data_quality_logs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("entity_type", sa.String(length=80), nullable=False),
        sa.Column("entity_id", sa.String(length=120), nullable=True),
        sa.Column("provider", sa.String(length=64), nullable=True),
        sa.Column("issue_code", sa.String(length=80), nullable=False),
        sa.Column("severity", sa.String(length=24), nullable=False),
        sa.Column("data_state", sa.String(length=32), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("detected_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("context", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "stocks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("symbol", sa.String(length=16), nullable=False),
        sa.Column("name_ko", sa.String(length=200), nullable=False),
        sa.Column("market_code", sa.String(length=32), nullable=True),
        sa.Column("security_type", sa.String(length=64), nullable=True),
        sa.Column("listed_on", sa.Date(), nullable=True),
        sa.Column("delisted_on", sa.Date(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("source_provider", sa.String(length=64), nullable=False),
        sa.Column("source_function", sa.String(length=160), nullable=False),
        sa.Column("data_state", sa.String(length=32), nullable=False),
        sa.Column("as_of_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("collected_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("data_timing", sa.String(length=32), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("symbol"),
    )
    op.create_table(
        "audit_opinions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("stock_id", sa.Integer(), nullable=False),
        sa.Column("receipt_no", sa.String(length=32), nullable=False),
        sa.Column("original_receipt_no", sa.String(length=32), nullable=True),
        sa.Column("business_year", sa.Integer(), nullable=False),
        sa.Column("fiscal_date", sa.Date(), nullable=True),
        sa.Column("auditor", sa.String(length=200), nullable=True),
        sa.Column("opinion", sa.String(length=200), nullable=True),
        sa.Column("special_matter", sa.Text(), nullable=True),
        sa.Column("emphasis_matter", sa.Text(), nullable=True),
        sa.Column("core_audit_matter", sa.Text(), nullable=True),
        sa.Column("going_concern_risk", sa.Boolean(), nullable=True),
        sa.Column("internal_control_issue", sa.Boolean(), nullable=True),
        sa.Column("is_correction", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("source_provider", sa.String(length=64), nullable=False),
        sa.Column("source_function", sa.String(length=160), nullable=False),
        sa.Column("data_state", sa.String(length=32), nullable=False),
        sa.Column("as_of_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("collected_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("data_timing", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(["stock_id"], ["stocks.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("receipt_no", name="uq_audit_opinion_receipt"),
    )
    op.create_table(
        "disclosures",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("stock_id", sa.Integer(), nullable=True),
        sa.Column("raw_response_id", sa.Integer(), nullable=True),
        sa.Column("corp_code", sa.String(length=16), nullable=True),
        sa.Column("receipt_no", sa.String(length=32), nullable=False),
        sa.Column("original_receipt_no", sa.String(length=32), nullable=True),
        sa.Column("report_name", sa.String(length=400), nullable=False),
        sa.Column("receipt_date", sa.Date(), nullable=False),
        sa.Column("filer_name", sa.String(length=200), nullable=True),
        sa.Column("disclosure_type", sa.String(length=80), nullable=True),
        sa.Column("correction_note", sa.Text(), nullable=True),
        sa.Column("is_correction", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("source_provider", sa.String(length=64), nullable=False),
        sa.Column("source_function", sa.String(length=160), nullable=False),
        sa.Column("data_state", sa.String(length=32), nullable=False),
        sa.Column("as_of_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("collected_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("data_timing", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(
            ["raw_response_id"], ["api_raw_responses.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["stock_id"], ["stocks.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("receipt_no"),
    )
    op.create_table(
        "dividends",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("stock_id", sa.Integer(), nullable=False),
        sa.Column("receipt_no", sa.String(length=32), nullable=True),
        sa.Column("original_receipt_no", sa.String(length=32), nullable=True),
        sa.Column("business_year", sa.Integer(), nullable=False),
        sa.Column("stock_kind", sa.String(length=80), nullable=True),
        sa.Column("dividend_type", sa.String(length=80), nullable=True),
        sa.Column("dps", sa.Numeric(precision=24, scale=6), nullable=True),
        sa.Column("currency", sa.String(length=12), nullable=True),
        sa.Column("total_amount", sa.Numeric(precision=30, scale=2), nullable=True),
        sa.Column("record_date", sa.Date(), nullable=True),
        sa.Column("payment_date", sa.Date(), nullable=True),
        sa.Column("is_confirmed", sa.Boolean(), nullable=True),
        sa.Column("is_estimate", sa.Boolean(), nullable=True),
        sa.Column("is_correction", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("source_provider", sa.String(length=64), nullable=False),
        sa.Column("source_function", sa.String(length=160), nullable=False),
        sa.Column("data_state", sa.String(length=32), nullable=False),
        sa.Column("as_of_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("collected_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("data_timing", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(["stock_id"], ["stocks.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("dividends", schema=None) as batch_op:
        batch_op.create_index(
            "ix_dividends_stock_business_year",
            ["stock_id", "business_year"],
            unique=False,
        )

    op.create_table(
        "financial_metrics",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("stock_id", sa.Integer(), nullable=False),
        sa.Column("metric_code", sa.String(length=80), nullable=False),
        sa.Column("value", sa.Numeric(precision=30, scale=10), nullable=True),
        sa.Column("unit", sa.String(length=40), nullable=True),
        sa.Column("period_start", sa.Date(), nullable=True),
        sa.Column("period_end", sa.Date(), nullable=False),
        sa.Column("fs_div", sa.String(length=3), nullable=True),
        sa.Column("rule_version", sa.String(length=40), nullable=False),
        sa.Column("input_data_hash", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("source_provider", sa.String(length=64), nullable=False),
        sa.Column("source_function", sa.String(length=160), nullable=False),
        sa.Column("data_state", sa.String(length=32), nullable=False),
        sa.Column("as_of_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("collected_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("data_timing", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(["stock_id"], ["stocks.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "stock_id",
            "metric_code",
            "period_end",
            "fs_div",
            "rule_version",
            name="uq_financial_metric_version",
        ),
    )
    op.create_table(
        "financial_statements",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("stock_id", sa.Integer(), nullable=False),
        sa.Column("corp_code", sa.String(length=16), nullable=False),
        sa.Column("receipt_no", sa.String(length=32), nullable=False),
        sa.Column("original_receipt_no", sa.String(length=32), nullable=True),
        sa.Column("report_code", sa.String(length=16), nullable=False),
        sa.Column("business_year", sa.Integer(), nullable=False),
        sa.Column("statement_kind", sa.String(length=32), nullable=False),
        sa.Column("fs_div", sa.String(length=3), nullable=False),
        sa.Column("period_start", sa.Date(), nullable=True),
        sa.Column("period_end", sa.Date(), nullable=False),
        sa.Column("filing_date", sa.Date(), nullable=False),
        sa.Column("is_cumulative", sa.Boolean(), nullable=True),
        sa.Column("is_correction", sa.Boolean(), nullable=False),
        sa.Column("currency", sa.String(length=12), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("source_provider", sa.String(length=64), nullable=False),
        sa.Column("source_function", sa.String(length=160), nullable=False),
        sa.Column("data_state", sa.String(length=32), nullable=False),
        sa.Column("as_of_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("collected_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("data_timing", sa.String(length=32), nullable=False),
        sa.CheckConstraint("fs_div IN ('CFS', 'OFS')", name="ck_fs_div"),
        sa.ForeignKeyConstraint(["stock_id"], ["stocks.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "receipt_no",
            "statement_kind",
            "fs_div",
            name="uq_financial_statement_receipt",
        ),
    )
    op.create_table(
        "market_status",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("stock_id", sa.Integer(), nullable=True),
        sa.Column("status_type", sa.String(length=80), nullable=False),
        sa.Column("status_value", sa.String(length=120), nullable=False),
        sa.Column("effective_from", sa.DateTime(timezone=True), nullable=False),
        sa.Column("effective_to", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("source_provider", sa.String(length=64), nullable=False),
        sa.Column("source_function", sa.String(length=160), nullable=False),
        sa.Column("data_state", sa.String(length=32), nullable=False),
        sa.Column("as_of_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("collected_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("data_timing", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(["stock_id"], ["stocks.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("market_status", schema=None) as batch_op:
        batch_op.create_index(
            "ix_market_status_stock_effective",
            ["stock_id", "effective_from"],
            unique=False,
        )

    op.create_table(
        "price_daily",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("stock_id", sa.Integer(), nullable=False),
        sa.Column("trade_date", sa.Date(), nullable=False),
        sa.Column("currency", sa.String(length=12), nullable=True),
        sa.Column("open_price", sa.Numeric(precision=24, scale=6), nullable=True),
        sa.Column("high_price", sa.Numeric(precision=24, scale=6), nullable=True),
        sa.Column("low_price", sa.Numeric(precision=24, scale=6), nullable=True),
        sa.Column("close_price", sa.Numeric(precision=24, scale=6), nullable=True),
        sa.Column("volume", sa.Numeric(precision=30, scale=0), nullable=True),
        sa.Column("trading_value", sa.Numeric(precision=30, scale=2), nullable=True),
        sa.Column("market_cap", sa.Numeric(precision=30, scale=2), nullable=True),
        sa.Column("listed_shares", sa.Numeric(precision=30, scale=0), nullable=True),
        sa.Column("is_adjusted", sa.Boolean(), nullable=True),
        sa.Column("adjustment_status", sa.String(length=40), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("source_provider", sa.String(length=64), nullable=False),
        sa.Column("source_function", sa.String(length=160), nullable=False),
        sa.Column("data_state", sa.String(length=32), nullable=False),
        sa.Column("as_of_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("collected_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("data_timing", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(["stock_id"], ["stocks.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "stock_id", "trade_date", "source_provider", name="uq_price_daily_source"
        ),
    )
    with op.batch_alter_table("price_daily", schema=None) as batch_op:
        batch_op.create_index("ix_price_daily_trade_date", ["trade_date"], unique=False)

    op.create_table(
        "score_snapshots",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("stock_id", sa.Integer(), nullable=False),
        sa.Column("as_of_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("score_version", sa.String(length=40), nullable=False),
        sa.Column("rule_version", sa.String(length=40), nullable=False),
        sa.Column("input_data_hash", sa.String(length=64), nullable=False),
        sa.Column("investment_score", sa.Numeric(precision=7, scale=3), nullable=True),
        sa.Column("entry_score", sa.Numeric(precision=7, scale=3), nullable=True),
        sa.Column("data_confidence", sa.Numeric(precision=7, scale=3), nullable=True),
        sa.Column("data_state", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "data_confidence IS NULL OR (data_confidence >= 0 AND data_confidence <= 100)",
            name="ck_data_confidence_range",
        ),
        sa.CheckConstraint(
            "entry_score IS NULL OR (entry_score >= 0 AND entry_score <= 100)",
            name="ck_entry_score_range",
        ),
        sa.CheckConstraint(
            "investment_score IS NULL OR (investment_score >= 0 AND investment_score <= 100)",
            name="ck_investment_score_range",
        ),
        sa.ForeignKeyConstraint(["stock_id"], ["stocks.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "stock_id",
            "as_of_at",
            "score_version",
            "rule_version",
            "input_data_hash",
            name="uq_score_snapshot_reproducible",
        ),
    )
    op.create_table(
        "stock_classifications",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("stock_id", sa.Integer(), nullable=False),
        sa.Column("classification_system", sa.String(length=80), nullable=False),
        sa.Column("classification_code", sa.String(length=80), nullable=False),
        sa.Column("classification_name", sa.String(length=200), nullable=True),
        sa.Column("valid_from", sa.Date(), nullable=True),
        sa.Column("valid_to", sa.Date(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("source_provider", sa.String(length=64), nullable=False),
        sa.Column("source_function", sa.String(length=160), nullable=False),
        sa.Column("data_state", sa.String(length=32), nullable=False),
        sa.Column("as_of_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("collected_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("data_timing", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(["stock_id"], ["stocks.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "stock_id",
            "classification_system",
            "classification_code",
            "valid_from",
            name="uq_stock_classification_version",
        ),
    )
    op.create_table(
        "financial_accounts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("statement_id", sa.Integer(), nullable=False),
        sa.Column("account_id", sa.String(length=200), nullable=True),
        sa.Column("account_name", sa.String(length=300), nullable=False),
        sa.Column("account_detail", sa.String(length=300), nullable=True),
        sa.Column("statement_section", sa.String(length=40), nullable=True),
        sa.Column("amount", sa.Numeric(precision=30, scale=6), nullable=True),
        sa.Column("unit", sa.String(length=40), nullable=True),
        sa.Column("mapping_status", sa.String(length=32), nullable=False),
        sa.Column("raw_label", sa.String(length=300), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["statement_id"], ["financial_statements.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "statement_id",
            "account_id",
            "account_detail",
            name="uq_financial_account_context",
        ),
    )
    op.create_table(
        "recommendations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("stock_id", sa.Integer(), nullable=False),
        sa.Column("score_snapshot_id", sa.Integer(), nullable=True),
        sa.Column("as_of_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("recommendation_type", sa.String(length=80), nullable=False),
        sa.Column("reason_summary", sa.Text(), nullable=True),
        sa.Column("score_version", sa.String(length=40), nullable=False),
        sa.Column("rule_version", sa.String(length=40), nullable=False),
        sa.Column("input_data_hash", sa.String(length=64), nullable=False),
        sa.Column("data_state", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["score_snapshot_id"], ["score_snapshots.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["stock_id"], ["stocks.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "stock_id",
            "as_of_at",
            "score_version",
            "rule_version",
            "input_data_hash",
            name="uq_recommendation_reproducible",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("recommendations")
    op.drop_table("financial_accounts")
    op.drop_table("stock_classifications")
    op.drop_table("score_snapshots")
    with op.batch_alter_table("price_daily", schema=None) as batch_op:
        batch_op.drop_index("ix_price_daily_trade_date")

    op.drop_table("price_daily")
    with op.batch_alter_table("market_status", schema=None) as batch_op:
        batch_op.drop_index("ix_market_status_stock_effective")

    op.drop_table("market_status")
    op.drop_table("financial_statements")
    op.drop_table("financial_metrics")
    with op.batch_alter_table("dividends", schema=None) as batch_op:
        batch_op.drop_index("ix_dividends_stock_business_year")

    op.drop_table("dividends")
    op.drop_table("disclosures")
    op.drop_table("audit_opinions")
    op.drop_table("stocks")
    op.drop_table("data_quality_logs")
    op.drop_table("api_raw_responses")
    # ### end Alembic commands ###
